# Generated by Django 3.0.8 on 2020-08-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='urls',
            field=models.ManyToManyField(blank=True, related_name='urls', to='api.url'),
        ),
    ]
