# Generated by Django 3.0.8 on 2020-08-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200801_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
