# Generated by Django 3.0.8 on 2020-08-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='api.Keyword'),
        ),
    ]
