# Generated by Django 3.0.8 on 2020-08-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_url_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('EXP', models.IntegerField()),
                ('FINAL_XP', models.IntegerField()),
                ('MULTIPLIER', models.IntegerField()),
            ],
        ),
    ]
